# Generated by Django 3.0.8 on 2020-09-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_carengine_power_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carengine',
            name='eco_estimated_fuel_reduction',
            field=models.IntegerField(blank=True, help_text='Enter The Estimated Fuel Reduction(%)', null=True),
        ),
        migrations.AlterField(
            model_name='carengine',
            name='eco_price',
            field=models.IntegerField(blank=True, help_text='Enter The Price(€)', null=True),
        ),
        migrations.AlterField(
            model_name='carengine',
            name='eco_torque_difference',
            field=models.IntegerField(blank=True, help_text='Enter The Difference Value(Nm)', null=True),
        ),
        migrations.AlterField(
            model_name='carengine',
            name='eco_torque_origin',
            field=models.IntegerField(blank=True, help_text='Enter The Origin Value(Nm)', null=True),
        ),
    ]
